/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 */

import type { ConversationId } from './ConversationId';
import type { ResponseBase } from './ResponseBase';

/** Response to a request to start a conversation.
 *  The generated conversation ID is included in the output, in addition to any outgoing activities.
 */
export interface StartResponse extends ResponseBase {
  /**
   * The conversation ID that was generated by the system.
   */
  conversationId: ConversationId;
}
